### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by fastcolors** [rmrector/script.artwork.beef#1]
Is there a reason for changing thumbnails for items? there's no option to leave them untouched. 

I'd love the option to leave Kodi's default thumbs for items, while getting all the extra art.

**Comment by rmrector** [comment]
Artwork Beef should leave thumbnails alone unless there are artwork files that match ("[item name]-thumb.jpg" or "thumb.jpg", and "[item name]/folder.jpg" or "[item name]-folder.jpg" for sets, to match MSAA). I'm up for adding a switch to disable movie set "folder.jpg" files as thumbnails if that's the problem.

Otherwise, a quick check behaves as I'd expect. There are all sorts of things I may have missed, so I'll need more info. What type of media items is Artwork Beef changing the thumbnail for? What scraper are you using for them? What version of Kodi? A [debug log](http://kodi.wiki/view/Log_file/Easy) that includes Kodi startup, adding an affected media item then Artwork Beef changing its thumbnail may provide me with additional useful info.

**Comment by rmrector** [comment]
Kodi does generate a thumbnail for new movies if it doesn't have a poster (I disabled the poster from the scraper so that Artwork Beef would pick one). In this case, some skins or add-ons that request the ListItem.Thumb and expect it to fall back to the poster show the wrong image.

Does this sound like what you are seeing?

Either way, the next version of Artwork Beef will remove the generated thumbnail in this particular case to better match scraper behavior.

**Comment by rmrector** [comment]
Version 0.11.0 changed the way that thumb images are dealt with, and the changed mentioned in the last comment were removed. Skins should show a poster if they want a poster.

Going to close this, but if you have any further ideas or info it can be revisited.
